### ISSUE TITLE
Document how to build locally

### ISSUE THREAD

**Issue by n3f** [georgestagg/pandoc-wasm#3]
I'm curious about trying to build this locally, but noticed that there aren't any instructions.  It's possible that it's super simple, but I'm missing the required information to get started 😆.

**Comment by georgestagg** [comment]
It has been several months since I last looked at this, but from what I remember something like the following should work:

```bash
git clone https://github.com/georgestagg/pandoc-wasm.git
cd pandoc-wasm
make submodules
make docker-container
make all
```

This should ~~build~~ pull a docker container containing Asterius and pandoc's prerequisites, then run Asterius to build pandoc with the result written to the `./dist` directory.

Note that some Haskell packages will have updated releases since I last build the Wasm binary, you will likely need to add some additional fixed older versions of packages in the file `pandoc-wasm.cabal`.

EDIT: I've pushed an update so that running `make docker-container` pulls the pre-built Docker container distributed with this GitHub project. This avoids the issue above by providing Asterius and a working set of pre-built versions of Pandoc's prerequisites.

-----

The process begins with Asterius's docker image, so if you'd like to build locally outside Docker you'll also need to recreate the `terrorjack/asterius` container image in your local development environment. The Asterius source is at https://github.com/tweag/asterius, though is now archived.

In the future, when I return to this, I want to switch from Asterius to the [ghc wasm backend](https://gitlab.haskell.org/ghc/ghc-wasm-meta). When that happens there will be a completely new set of development instructions. At that point, I will add a `Development Build` section to the `README.md` file with relevant information on how to build the Wasm binary from scratch.

**Comment by frabera** [comment]
> It has been several months since I last looked at this, but from what I remember something like the following should work:
> 
> ```shell
> git clone https://github.com/georgestagg/pandoc-wasm.git
> cd pandoc-wasm
> make submodules
> make docker-container
> make all
> ```
> 
> This should build a docker container containing Asterius and pandoc's prerequisites, then run Asterius to build pandoc with the result written to the `./dist` directory.
> 
> Note that some Haskell packages will have updated releases since I last build the Wasm binary, you will likely need to add some additional fixed older versions of packages in the file `pandoc-wasm.cabal`.
> 
> EDIT: I've pushed an update so that running `make docker-container` pulls the pre-built Docker container distributed with this GitHub project. This avoids the issue above by providing Asterius and a working set of pre-built versions of Pandoc's prerequisites.
> 
> The process begins with Asterius's docker image, so if you'd like to build locally outside Docker you'll also need to recreate the `terrorjack/asterius` container image in your local development environment. The Asterius source is at https://github.com/tweag/asterius, though is now archived.
> 
> In the future, when I return to this, I want to switch from Asterius to the [ghc wasm backend](https://gitlab.haskell.org/ghc/ghc-wasm-meta). When that happens there will be a completely new set of development instructions. At that point, I will add a `Development Build` section to the `README.md` file with relevant information on how to build the Wasm binary from scratch.

Do you think that by switching to the ghc wasm backend will the following features work?

* Usage of the integrated citeproc engine
* Possibility to run or integrate haskell plugins (i.e. pandoc-crossref or similar)

**Comment by georgestagg** [comment]
There is now a Pandoc for WebAssembly engine built using the GHC Wasm backend. https://github.com/tweag/pandoc-wasm

I'm going to archive this project (closing this thread). I would recommend trying out Tweag's new pandoc-wasm project to see if it supports your needs!
